### ISSUE TITLE
Read options from a configuration file

### ISSUE THREAD

**Issue by daviebadger** [asottile/reorder_python_imports#101]
ideally `pyproject.toml`

**Comment by asottile** [comment]
I have no interest in supporting this, sorry

**Comment by asottile** [comment]
with more words, using a config file is something I both won't use and I don't think is worth the complexity (for example it's one of the most complicated parts of flake8).  there's also very few options and they aren't used very often (and you can already configure them statically through something like `tox.ini` or `.pre-commit-config.yaml`)

**Comment by daviebadger** [comment]
well, the reorder should be generic when running in a different pre-commit usage / framework, especially in a monorepo, where each package has its configs for CI (thus the configuration file, when no options is passed to the CLI)

**Comment by asottile** [comment]
sorry, no
