### ISSUE TITLE
Allow directory as an argument (no globbing or pre-commit uses)

### ISSUE THREAD

**Issue by daviebadger** [asottile/reorder_python_imports#102]

**Comment by asottile** [comment]
dupe #75

**Comment by daviebadger** [comment]
ehm, it still raises `IsADirectoryError: [Errno 21] Is a directory: 'package_name'` (using the latest 1.7.0 version), when running `reorder-python-imports package_name/`

**Comment by asottile** [comment]
did you read the linked issue? intentionally not implemented

**Comment by peterjc** [comment]
Was issue 75 a typo? It doesn't seem related to directories as arguments.

**Comment by asottile** [comment]
yep sorry that was supposed to be 76, updated
