### ISSUE TITLE
`from subprocess import check_output` is improperly sorted by reorder-python-imports pre-commit hook

### ISSUE THREAD

**Issue by ngie-eign** [asottile/reorder_python_imports#106]
The following import order is correct, per alphabetization:
```
$ cat reorder-python-imports-bug.py 
import errno
import os
import pwd
import shutil
from subprocess import check_output
import syslog
import time
```

When I run the pre-commit hook though, it incorrectly sorts the imports so `from subprocess import check_output` comes after the `syslog` and `time` imports:
```
$ cat reorder-python-imports-bug.py 
import errno
import os
import pwd
import shutil
import syslog
import time
from subprocess import check_output
```

This doesn't seem to be following the spirit of [PEP8](https://www.python.org/dev/peps/pep-0008/#imports).

#### Snippet from `.pre-commit-config.yaml`
```
61 -   repo: https://github.com/asottile/reorder_python_imports
62     rev: v1.8.0
63     hooks:
64     -     id: reorder-python-imports
65           language_version: python3
```

#### Program Version Information
```
$ pre-commit --version
pre-commit 1.20.0
$ head -n 1 `which pre-commit `
#!/usr/bin/python3
$ python3 --version
Python 3.7.5
```

Thought: is this occurring because subprocess is being considered a third-party module...?

**Comment by asottile** [comment]
https://github.com/asottile/reorder_python_imports#import-imports-before-from-imports
