### ISSUE TITLE
Linting comments/markers are deleted in import reordering

### ISSUE THREAD

**Issue by jmrf** [asottile/reorder_python_imports#110]
Import reordering doesn't take into account linter/checker comments.

Example:

Before:
```
from A import (  # pytype: disable=pyi-error
    b,
    c,
)
```

After:
```
from A import b
from A import c
```
Removing the `pytype` disabling marker.

Ideally should be something like:
```
from A import b   # pytype: disable=pyi-error
from A import c   # pytype: disable=pyi-error
```

**Comment by asottile** [comment]
this is unavoidable when splitting imports so you'll just have to do it manually

applying the comment to all is not always the correct thing (consider the following):

```python
from os import path, execvp  # noqa: F401

execvp('echo', ('echo', 'hi'))
```

after splitting you end up with one of these choices:

```python
from os import execvp
from os import path

execvp('echo', ('echo', 'hi'))
```

OR

```python
from os import execvp  # noqa: F401
from os import path  # noqa: F401

execvp('echo', ('echo', 'hi'))
```

when in reality, the correct output is:

```python
from os import execvp
from os import path  # noqa: F401

execvp('echo', ('echo', 'hi'))
```

(this is actually a good part of the motivation for splitting imports anyway!  now you can be explicit about exactly which import line you are ignoring).

Note that for normal reordering (not splitting) comments *are* preserved

**Comment by jmrf** [comment]
Thanks @asottile.

Yes, that makes sense, replicating the comment wouldn't always fix it either.

Would it make sense to output a warning in case of an "ambiguous" comment?
As in this case:

```python
from os import path, execvp  # noqa: F401
```

**Comment by asottile** [comment]
it's hard to know what is and isn't ambiguous and I don't really do warnings if they're not actionable
