### ISSUE TITLE
Document flake8-import-order compatibility (smarkets, edited, pep8?)

### ISSUE THREAD

**Issue by peterjc** [asottile/reorder_python_imports#112]
Is the ``reorder_python_imports`` output expected to always match any of the ``flake8-import-order`` styles?

https://github.com/PyCQA/flake8-import-order/blob/master/README.rst#styles

(My motivation is for enforcement via flake8, although I could move to the pre-commit package at some point)

On a small project I found the ``reorder_python_imports`` output matched ``flake8-import-order`` styles ``smarkets``, ``edited`` and ``pep8``:

```
$ for NAME in cryptography google smarkets appnexus edited pycharm pep8; do echo $NAME; flake8 --import-order-style $NAME --application-import-names thapbi_pict --isolated --select I . | wc -l; done
cryptography
      14
google
      10
smarkets
       0
appnexus
      10
edited
       0
pycharm
       7
pep8
       0
```

PEP8 itself says relatively little about import order, so while it is good that passes, this seems to be the most lenient of the defined styles:

The ``edited`` style does not seem to be well documented, but the example given differs from ``smarkets`` only in the imports for local packages.

* https://github.com/PyCQA/flake8-import-order/blob/master/tests/test_cases/complete_edited.py
* https://github.com/PyCQA/flake8-import-order/blob/master/tests/test_cases/complete_smarkets.py

Would you expect it to match either, or was it just a happy coincidence here?

**Comment by asottile** [comment]
I have no idea, I didn't intend to match anything specific :man_shrugging: -- the README denotes what the style chooses: https://github.com/asottile/reorder_python_imports#what-does-it-do

**Comment by peterjc** [comment]
Thanks - I suspected that might be the case. I've taken the pragmatic approach for now and in this project have configured ``flake8-import-order`` to use its most relaxed style just in case that plugin is installed locally.

**Comment by peterjc** [comment]
Revisiting this for another project, reorder-python-imports appears to match the ``pycharm`` and minimal ``pep8`` styles in ``flake8-import-order`` only.

Specifically it does not match ``smarkets`` due to case sorting, which is the only point of difference from the ``pycharm`` style. My original test case did not cover this.
