### ISSUE TITLE
reorder_python_imports -v or --version not implemented

### ISSUE THREAD

**Issue by peterjc** [asottile/reorder_python_imports#113]
It would be nice to support the ``-v`` or ``--version`` convention,

```
$ reorder_python_imports --version
1.5.1
```

**Comment by peterjc** [comment]
Assuming the version was defined in the main python script (e.g. as ``__version__``), this would be easy to do with ``argparse``, e.g.

```python
    parser.add_argument(
        "-v", "--version", action="version",
        version=f"reorder_python_imports v{__version__}"
    )
```

However, currently you have version set in ``setup.cfg`` - it would be a step away from declarative metadata but you could use something like this in your ``setup.py``:

```python
# We define the version number in reorder_python_imports.py
__version__ = "Undefined"
with open("reorder_python_imports.py") as handle:
    for line in handle:
        if line.startswith("__version__"):
            exec(line.strip())
            break
```

**Comment by asottile** [comment]
why doesn't `pip freeze` work?

**Comment by asottile** [comment]
(and if one would want to implement this correctly, one would use [`importlib.metadata`](https://docs.python.org/3/library/importlib.metadata.html) to query the installed version) -- this avoids a bunch of hacks with `__version__` / `setup.py` / etc.

**Comment by peterjc** [comment]
The ``-v`` and/or ``--version`` convention is far wider than just the Python community, so I expect this to be there regardless of the language the tool was written in.

As to your suggestion,  ``pip freeze`` doesn't just tell be your tool's version - you need a work around like:

```
$ pip freeze | grep reorder-python-imports
reorder-python-imports==1.9.0
```

Notice that now you need to worry about underscores versus minus signs, so this is a *fragile* workaround.

--

I don't like version hacks in ``setup.py`` either, so was curious to see how you'd might do this. I just tried ``importlib.metdata`` but it doesn't seem to be in the standard library until perhaps Python 3.8?

**Comment by asottile** [comment]
there's a backport, look at how pre-commit does this

**Comment by peterjc** [comment]
Thanks - that's useful. Yes, pre-commit uses the backport ``importlib_metadata`` prior to Python 3.8:

https://github.com/pre-commit/pre-commit/blob/v2.0.1/pre_commit/main.py#L165

https://github.com/pre-commit/pre-commit/blob/v2.0.1/pre_commit/constants.py#L18

```python
VERSION = importlib_metadata.version('pre_commit')
```

For now I'd prefer to avoid the backport dependency for this in my own tools.
