### ISSUE TITLE
Adjust ~wheel naming for py2 drop?

### ISSUE THREAD

**Issue by shea-parkes** [asottile/reorder_python_imports#115]
I went to go take a peek at PyPI and saw 2.0.0 up there.  I'm a bit rusty on ~wheel names, but it looks like the wheel name may still be indicating Python 2.x compatibility:

![image](https://user-images.githubusercontent.com/5782892/75482298-88885000-5972-11ea-9fdd-95d3b7fd4828.png)

**Comment by asottile** [comment]
it's just indicating a "pure python" wheel (universal = True) -- the `python_requires` limits it to python3.6:

(from source of pypi.org/simple/aspy.refactor_imports)
```
    <a href="https://files.pythonhosted.org/packages/bf/e8/0192d710ebdb8ece31ec075e84bd1157d6221f57669240494621c3423713/aspy.refactor_imports-2.0.0-py2.py3-none-any.whl#sha256=57406a439092af3e01463ebc7257ec2b1dcce4acddaf3a73a46aa351611cda40" data-requires-python="&gt;=3.6.1">aspy.refactor_imports-2.0.0-py2.py3-none-any.whl</a><br/>
    <a href="https://files.pythonhosted.org/packages/4c/32/94d9850744f64eb59fccc5570bb487ff0da70ee6ab22d2d653037bc49686/aspy.refactor_imports-2.0.0.tar.gz#sha256=1dc2937326029297312d5350b239531a4c1b6cbb4c0baf9a478c524c768ba430" data-requires-python="&gt;=3.6.1">aspy.refactor_imports-2.0.0.tar.gz</a><br/>
```

**Comment by shea-parkes** [comment]
Thanks for the background.  (And the quick release.)
