### ISSUE TITLE
Provide an option to disable splitting from imports

### ISSUE THREAD

**Issue by kbd** [asottile/reorder_python_imports#118]
It would be nice to have an option to disable [splitting `from` imports](https://github.com/asottile/reorder_python_imports#splits-from-imports). Otherwise, `reorder_python_imports` works exactly how I want.

**Comment by asottile** [comment]
nope sorry, that's half the point -- no settings => no arguments

it also goes against [the core rationale of the tool](https://github.com/asottile/reorder_python_imports#why-this-style)

I'm actually planning to remove all of the current conditional options

**Comment by kbd** [comment]
I respect your decision, of course. Just offering an alternative that I often do (when `from` imports span more than one line):

Instead of:

```python
from foo import bar
from foo import baz
```

Another option is:

```python
from foo import (
    bar,
    baz,
)
```

That way it groups imports from one module together and is still nice with source diffs.

**Comment by asottile** [comment]
sure, if you want a million options use isort :)
