### ISSUE TITLE
Question: Separates into three sections

### ISSUE THREAD

**Issue by sleighsoft** [asottile/reorder_python_imports#120]
First of all, thank you for the cool tool!

I would like to know what exactly you mean by "Separates into three sections". I don't seem to understand which those got separated.

-----------

Separates imports into three sections
```python
import sys
import pyramid
import reorder_python_imports
```
becomes
```python
import sys

import pyramid

import reorder_python_imports
```

**Comment by asottile** [comment]
stdlib, third party, first party

**Comment by sleighsoft** [comment]
Thank you :)
That wasn't very clear for me given the example.
