### ISSUE TITLE
Add lines after imports option?

### ISSUE THREAD

**Issue by proofit404** [asottile/reorder_python_imports#122]
Hi, thanks for the awesome project!

It would be nice to have an option to enforce 1 or 2 empty lines after import.

What do you think about it?

I could try to help if you think that this belongs to the package goal.

Have a good day :tada: 

Best regards,
Artem.

**Comment by asottile** [comment]
it used to do this (2) before #9

but turns out pep8 is inconsistent on lines here:

```python
import os

x = 5
```

```python
import os


def f(): pass
```

(these are both ok)

___

I don't really want to add options, and if it were to pick any value it would be 2 which would undo the fix from #9

**Comment by proofit404** [comment]
I didn't know about that.

I would prefer to enforce 2 spaces everywhere. But it only just my wish.

Feel free to close this issue if you don't want to push such constraints for all users.

Thanks for the quick response!

**Comment by asottile** [comment]
no problem and thanks for the issue!
