### ISSUE TITLE
Any chance multiple imports on one line could be considered?

### ISSUE THREAD

**Issue by TheButlah** [asottile/reorder_python_imports#129]
I suspect this goes against the design philosophy of this tool, but I thought I'd ask anyway.

I 100% agree that one import per line is ideal for avoiding merge conflicts, and is a very compelling reason to use this tool. However, I wanted to know if you would consider adding a command line option to offer some ability to allow multiple imports in one line.

The reason for this is as follows: avoiding merge conflicts is only one of several benefits of this tool over `isort`. In particular, I think that the static analysis, out of box compatibility with `pre-commit` and `black`, not needing an activated venv (unlike `isort`), and the simplicity of the tool are good selling points as well.

In my case, I came across this tool due to the aforementioned issues with `isort`, and while I believe that avoiding merge conflicts is worth the longer number of lines at the top of every python file, my coworkers don't think so, so I'll probably have to go back to `isort` due to the absence of this feature, at least in terms of my professional environment.

Totally understand if you're not willing to add the feature, but thought I'd ask anyway.

**Comment by asottile** [comment]
yeah sorry it's not going to happen as it goes against the design goals of the tool (no options, minimize merge conflicts)  if it were to allow multiple imports on one line, that causes problems in those areas.

**Comment by TheButlah** [comment]
Fair nuff

**Comment by asottile** [comment]
not sure why your coworkers care about number of lines :P

**Comment by TheButlah** [comment]
It be like that sometimes - people are picky about formatting
