### ISSUE TITLE
Generate black compatible isort result

### ISSUE THREAD

**Issue by dkdndes** [asottile/reorder_python_imports#132]
If I use "isort" in the following way I achieve a [black](https://github.com/psf/black) compatible result:

     $ isort --multi-line=3 --trailing-comma --force-grid-wrap=0 --use-parentheses --line-width=88 -vb -y

Use "-c" if I you just like to check within a pipeline.

**Comment by asottile** [comment]
cool?   this isn't isort and is already black compatible out of the box
