### ISSUE TITLE
pip lists latest version as 2.3.1, but latest tag is 2.3.0

### ISSUE THREAD

**Issue by gnikonorov** [asottile/reorder_python_imports#133]
Hi,

The latest version for this according to this repos tags is [2.3.0](https://github.com/asottile/reorder_python_imports/tags)

However, pypi has the latest version as [2.3.1](https://pypi.org/project/reorder-python-imports/)

Using 2.3.1 breaks things like pre-commit:
```
[INFO] Initializing environment for https://github.com/asottile/reorder_python_imports.
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'checkout', 'v2.3.1')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    error: pathspec 'v2.3.1' did not match any file(s) known to git.
```
Can we remove v2.3.1 from pypi or publish a v2.3.1 if it was deleted by accident?

**Comment by asottile** [comment]
deleting from pypi is never a good idea

**Comment by gnikonorov** [comment]
agreed, not sure why I suggested that. I'm curious where did 3.7.1 go?

**Comment by asottile** [comment]
most like I forgot to push, idk

**Comment by asottile** [comment]
the contents are byte identical with 2.3.2

**Comment by gnikonorov** [comment]
Thanks for the quick response @asottile
