### ISSUE TITLE
--separate-relative inserts a new line even when it is not really needed

### ISSUE THREAD

**Issue by pmav99** [asottile/reorder_python_imports#134]
Hey Anthony

It seems that `--separate-relative` inserts a new line even when it is not really needed (e.g. when you only have relative imports). 

### Reproducer

```
mkdir my_package
touch my_package/{a,b,__init__}.py
cat <<EOF >> my_package/__init__.py
from .a import *  # noqa 
from .b import *  # noqa 
EOF
```

```
$ reorder-python-imports --py38-plus --separate-relative --separate-from-import --diff-only my_package/__init__.py 
--- my_package/__init__.py
+++ my_package/__init__.py
@@ -1,2 +1,3 @@
+
 from .a import *  # noqa 
 from .b import *  # noqa 
```

If you want I can have a look 

### Pre-commit + pyupgrade

This new line was actually causing problems with `pre-commit` though and at least initially it was relatively hard to understand why the hooks were failing.

I had both `reorder-python-imports` and `pyupgrade` (in this order) and to the extend that I can understand this, they were probably creating "conflicting" patches, or perhaps more precisely, patches which when applied were resulting in the original file. I.e. `reorder-python-imports` was adding a newline and `pyupgrade` was removing it.

This way the hooks were always failing no matter how many times you run them.

Not sure if there is something that can be done about this case, but If you want I can open a ticket on `pre-commit`.

**Comment by pmav99** [comment]
https://github.com/asottile/reorder_python_imports/pull/24

**Comment by pmav99** [comment]
This seems to be fixing it:

```diff
diff --git a/reorder_python_imports.py b/reorder_python_imports.py
index 37d0ba5..4c4ba0d 100644
--- a/reorder_python_imports.py
+++ b/reorder_python_imports.py
@@ -384,7 +384,7 @@ def apply_import_sorting(
         if last_import_obj is not None:
             new_imports.append(CodePartition(CodeType.NON_CODE, '\n'))
 
-    if relative_imports:
+    if relative_imports and len(sorted_blocks) > 1:
         relative_imports.insert(0, CodePartition(CodeType.NON_CODE, '\n'))
     # XXX: I want something like [x].join(...) (like str join) but for now
     # this works
diff --git a/tests/reorder_python_imports_test.py b/tests/reorder_python_imports_test.py
index 756d586..71c73e6 100644
--- a/tests/reorder_python_imports_test.py
+++ b/tests/reorder_python_imports_test.py
@@ -891,6 +891,19 @@ def test_separate_relative_and_separate_from():
     )
 
 
+def test_separate_relative_and_separate_from_when_only_relative_imports_are_present():
+    ret = fix_file_contents(
+        'from . import bar\n'
+        'from . import foo\n',
+        separate_from_import=True,
+        separate_relative=True,
+    )
+    assert ret == (
+        'from . import bar\n'
+        'from . import foo\n'
+    )
+
+
 def test_fix_crlf():
     s = (
         '"""foo"""\r\n'
```

**Comment by asottile** [comment]
fwiw I'm probably going to remove this option at some point due to the number of weird edge cases it causes, but in the meantime would you like to send a PR?

**Comment by asottile** [comment]
reopening as this change caused a regression and was reverted (see #136)
