### ISSUE TITLE
Option --diff-only not working with input from stdin

### ISSUE THREAD

**Issue by ggicci** [asottile/reorder_python_imports#140]
When input from stdin, diff reporting is not working.

```bash
reorder-python-imports - --diff-only
import banana
import apple
<Ctrl+D>
```

Expected output:

```
@@ -1,2 +1,2 @@
+import apple
 import banana
-import apple
```

But it produced:

```
import apple
import banana
```

The output is not a unified diff, but the final reordered content.

**Comment by asottile** [comment]
fwiw I'm likely going to remove the `--diff-only` mode in the future -- you can probably use `reorder-python-imports /dev/stdin --diff-only` if you want

**Comment by ggicci** [comment]
It's common to write `stdin` as a dash (`-`). I think it will be helpful when this issue was fixed. For example, it can be utilized by vscode-python extension to sort imports for python files. Which is also requested in #117.
