### ISSUE TITLE
Add support for passing directories to CLI

### ISSUE THREAD

**Issue by enpaul** [asottile/reorder_python_imports#143]
I was wondering if it would be possible to add functionality for passing in directories to the CLI like the example command below:
```
reorder-python-imports ./my_module/
```

Currently, the above command gives a traceback like the below:
```
Traceback (most recent call last):
  File ".venv/bin/reorder-python-imports", line 8, in <module>
    sys.exit(main())
  File ".venv/lib/python3.8/site-packages/reorder_python_imports.py", line 852, in main
    retv |= _fix_file(filename, args)
  File ".venv/lib/python3.8/site-packages/reorder_python_imports.py", line 463, in _fix_file
    with open(filename, 'rb') as f:
IsADirectoryError: [Errno 21] Is a directory: './my_module/'
```

Another possibility might be to add an explicit `-r, --recurse` flag to indicate that directories should be traversed. 

The work around I've used up to now is to glob files using my shell (i.e. `reorder-python-imports ./my_module/*.py`) however this runs into problems when using this tool with shell-less automation like [Tox](https://tox.readthedocs.io/en/latest/). The work around in Tox specifically is to allow bash to be invoked as an external program and then wrap the call to `reorder-python-imports` in bash, like the below `tox.ini` excerpt:

```ini
...
allowlist_externals =
    bash
commands =
    bash -c "reorder-python-imports my_module/*.py"
...

However this feels brittle to me and I'd like to be able to pass directories into the tool natively to avoid having to rely on a shell to do the globbing for me. In addition, using globbing like the above examples doesn't account for subdirectories that may also need processing.

Thank you so much for your work on this tool, I've been incredibly happy with using it in my projects. If this is a feature you'd be ok with adding I may also be able to work on implementing it.

**Comment by asottile** [comment]
dupe #102 #76
