### ISSUE TITLE
Keep a changelog

### ISSUE THREAD

**Issue by underyx** [asottile/reorder_python_imports#153]
Please keep a changelog. I just spent around 5 minutes trying to find what changed in 2021 February's new version, but couldn't figure it out.

https://keepachangelog.com/en/1.0.0/

**Comment by asottile** [comment]
no thanks, you can run `git log` pretty easily

**Comment by underyx** [comment]
I respect that you can decline any request from users as you see fit, and appreciate that you provide your work to everyone for free.

With no expectation that you change your mind, I will mention an additional datapoint, that as a maintainer of open source projects myself, I'm immensely grateful whenever I don't need to spend time and energy to go through all the commits between two versions, sift through merge commits, keep track of what's been reverted, skip over documentation or version bump changes, double check if the project keeps accurate commit messages or they tend to squash multiple messages into one or sometimes bundle unrelated modifications in the same commit, and so on.

My principle is that as the maintainer I can do this once and save hundreds of users the trouble. As maintainer I'm also the one person who can most efficiently parse the commit log of my own project.

I respect if you don't feel up to this extra time commitment. Could you at least commit a blank changelog file, to explain that people can rely on the commit messages and should not expect to find release notes anywhere? (That would at least save us the trouble of checking GitHub release descriptions, git tag messages, the whole README, any possible documentation site, and the PyPI package description, hoping to find a changelog.)

**Comment by asottile** [comment]
no, and I don't appreciate your attitude
