### ISSUE TITLE
How to exclude a path?

### ISSUE THREAD

**Issue by Zethson** [asottile/reorder_python_imports#162]
I need to exclude a full folder from the reordering. Ideally it would be possible to configure this in the pyproject.toml file in a tool section.

**Comment by asottile** [comment]
there's no need for every tool to implement this poorly when [`exclude`](https://pre-commit.com/#config-exclude) works

also lol pyproject.toml, surely you jest

**Comment by Zethson** [comment]
Sorry, didn't know that pre-commit exclude works for this. Didn't see this in this README.

**Comment by asottile** [comment]
yeah there's no need to duplicate the documentation for every option from pre-commit everywhere poorly
