### ISSUE TITLE
`import` being sorted after `from` statements

### ISSUE THREAD

**Issue by NazarioJL** [asottile/reorder_python_imports#165]
After running `pre-commit run reorder-python-imports` I am getting the following diff:

```diff
-import attr
-
 from enum import Enum
 from typing import List
 from typing import Optional

+import attr
+
```

For some the import which I would expect to happen [before](https://github.com/asottile/reorder_python_imports/blame/master/README.md#L71) the from statements is getting pushed down.

**Comment by asottile** [comment]
https://github.com/asottile/reorder_python_imports#separates-imports-into-three-sections
