### ISSUE TITLE
From __future__ import annotations deprecation postponed

### ISSUE THREAD

**Issue by SalomonSmeke** [asottile/reorder_python_imports#168]
FYI: https://bugs.python.org/issue38605

won't be automatically imported until python 3.11.

```
--py310-plus: annotations
```

should be

```
--py311-plus: annotations
```

**Comment by asottile** [comment]
this was already fixed: #163

**Comment by SalomonSmeke** [comment]
Ack! I was confused since the documentation lists py10 in the readme.
