### ISSUE TITLE
Add support for imports within parenthesis

### ISSUE THREAD

**Issue by jaraqueffdc** [asottile/reorder_python_imports#173]
Hi!

I am thinking about introducing this tool in our team to improve a lot the import structure. We have many new people working with python for the first time and the import structure is becoming a bit of a pain.

However, the way imports are split in different lines conflicts with our style guide which is also taken from Black (so I imagine this will also conflict with people using Black).

My proposal (or question in case this is supported and I just don't know how) is to allow import splitting to be done within groups if an option is defined to do so.

```python
# This
from pathlib import Path, PurePath

# Would become this
from pathlib import (
    Path,
    PurePath,
)
```

This still keeps the idea of reducing merge conflicts that guides the tool while also avoiding code repetition and being aligned with a widely use formatter like Black.

Would this be something you might be consider? Thanks!

**Comment by MarcoGorelli** [comment]
> Would this be something you might be consider?

@jaraqueffdc if not, you can accomplish this with isort with `force_grid_wrap = True`, as is done in [pandas](https://github.com/pandas-dev/pandas/blob/master/pandas/core/generic.py)

**Comment by asottile** [comment]
no configuration means no configuration

**Comment by jaraqueffdc** [comment]
> @jaraqueffdc if not, you can accomplish this with isort with `force_grid_wrap = True`, as is done in [pandas](https://github.com/pandas-dev/pandas/blob/master/pandas/core/generic.py)

Thanks @MarcoGorelli it looks like isort is what I was looking for 🙂
