### ISSUE TITLE
Wrong sort when using local package import

### ISSUE THREAD

**Issue by kevinpita** [asottile/reorder_python_imports#180]
Hi, I have been using isort for a while but I saw this project and the idea to avoid merge conflicts and decided to give a try, I had the following code code

```
from datetime import datetime

from sqlalchemy import BigInteger, Column, DateTime, Integer, SmallInteger
from sqlalchemy.schema import ForeignKeyConstraint

from reputationbot.config import Base

```

but when running reorder-python-imports I get

```
from datetime import datetime

from reputationbot.config import Base
from sqlalchemy import BigInteger
from sqlalchemy import Column
from sqlalchemy import DateTime
from sqlalchemy import Integer
from sqlalchemy import SmallInteger
from sqlalchemy.schema import ForeignKeyConstraint

```

So I think this is wrong as reputationbot is a local package and should not be in the same block as third parties

**Comment by asottile** [comment]
you have not provided enough information, notably your code layout

but a guess you are using src layout and the readme covers this

**Comment by kevinpita** [comment]
> you have not provided enough information, notably your code layout
> 
> but a guess you are using src layout and the readme covers this

Fixed, sorry, as I was using a pre-commit hook I didnt read CLI
