### ISSUE TITLE
Issues when package is installed in virtualenv

### ISSUE THREAD

**Issue by WhyNotHugo** [asottile/reorder_python_imports#185]
I'm having issues when the package I'm editing is present in my current virtualenv.

I run `pip install -e .` for my packages, since they're `cli` apps, and that's the easiest way to test them.

When the package I'm editing is installed in the current virtualenv, it's treated as third party instead of first party.

Any hints on how to work around this? Or have I come across a bug?

**Comment by asottile** [comment]
my guess is you've not properly set `--application-directories` -- though you haven't provided a full reproduction so I can only guess.

for what it's worth, it works correctly for me with editable installs

**Comment by WhyNotHugo** [comment]
I'm not setting it. Can I configure that via setup.py / pyproject.yaml or something?

Isn't it possible to programmatically detect if the file being reordered is in `pwd`?

**Comment by asottile** [comment]
you can configure it via `args: [...]` or by passing it on the command line.  you still haven't shown me your problem so I still can't help you -- please show a reproducible case so I can run it and guide you to a solution instead of having to guess at the problem.

**Comment by WhyNotHugo** [comment]
It happens on this repo:

https://github.com/pimutils/vdirsyncer

Run `reorder-python-imports vdirsyncer/storage/dav.py`. It moves `vdirsyncer` into third-party. Oddly, the pre-commit hook works as intended.

**Comment by asottile** [comment]
does not reproduce:

```console
$ virtualenv venv
created virtual environment CPython3.8.10.final.0-64 in 275ms
  creator CPython3Posix(dest=/tmp/z/vdirsyncer/venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/asottile/.local/share/virtualenv)
    added seed packages: pip==21.1.3, setuptools==57.1.0, wheel==0.36.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
$ . venv/bin/activate
$ pip install -e .
Obtaining file:///tmp/z/vdirsyncer
Collecting click<9.0,>=5.0
...
$ reorder-python-imports vdirsyncer/storage/dav.py 
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

**Comment by WhyNotHugo** [comment]
I realised I was on reorder-python-imports 2.5.0, but upgraded to 2.6.0 and it's still an issue.

`vdirsyncer` is also installed system-side (e.g.: via my distribution's package manager). Do you think that could be related?

**Comment by WhyNotHugo** [comment]
So it seems to happen regardless of whether the virtualenv is active or not actually.

The only think I see unusual about this package is that it's installed on on my system python too (since it's a cli tool I actually use).

Reproduction:

```console
$ git clone git@github.com:pimutils/vdirsyncer.git
Cloning into 'vdirsyncer'...
Confirm user presence for key ED25519-SK SHA256:pXQ62ghWiAKayDFMRM+CmmdwyOOrdVyuUfIJyPTwLj8
User presence confirmed
remote: Enumerating objects: 13130, done.
remote: Counting objects: 100% (900/900), done.
remote: Compressing objects: 100% (443/443), done.
remote: Total 13130 (delta 497), reused 790 (delta 437), pack-reused 12230
Receiving objects: 100% (13130/13130), 2.95 MiB | 2.74 MiB/s, done.
Resolving deltas: 100% (9202/9202), done.

$ cd vdirsyncer

$ reorder-python-imports vdirsyncer/storage/dav.py
Reordering imports in vdirsyncer/storage/dav.py

$ git diff
diff --git a/vdirsyncer/storage/dav.py b/vdirsyncer/storage/dav.py
index 1743265..eb537cd 100644
--- a/vdirsyncer/storage/dav.py
+++ b/vdirsyncer/storage/dav.py
@@ -7,6 +7,7 @@ from inspect import signature

 import aiohttp
 import aiostream
+from vdirsyncer.exceptions import Error

 from .. import exceptions
 from .. import http
@@ -18,7 +19,6 @@ from ..http import USERAGENT
 from ..vobject import Item
 from .base import normalize_meta_value
 from .base import Storage
-from vdirsyncer.exceptions import Error


 dav_logger = logging.getLogger(__name__)

$ which reorder-python-imports
/usr/bin/reorder-python-imports

$ pip list
Package                       Version
----------------------------- ---------------------------------------------------------------------------------
abydos                        0.5.0
aiohttp                       3.7.4.post0
aiohttp-oauthlib              0.1.0
aiohttp-socks                 0.4.2
aioresponses                  0.7.2
aiorpcX                       0.18.7
aiostream                     0.4.3
alabaster                     0.7.12
ansible                       4.3.0
ansible-core                  2.11.3
apipkg                        1.5
appdirs                       1.4.4
argcomplete                   1.12.1
argh                          0.26.2
argon2-cffi                   20.1.0
arrow                         1.1.1
aspy.refactor-imports         2.2.0
astroid                       2.5.8
asttokens                     2.0.5
async-generator               1.10
async-timeout                 3.0.1
atomicwrites                  1.4.0
attrs                         21.2.0
Automat                       20.2.0
autopep8                      1.5.7
awscli                        1.20.2
awslogs                       0.14.0
Babel                         2.9.1
backcall                      0.2.0
bcrypt                        3.2.0
Beaker                        1.11.0
binaryornot                   0.4.4
bitstring                     3.1.7
black                         21.7b0
bleach                        3.3.1
boto3                         1.18.2
botocore                      1.21.2
breezy                        3.2.0
Brlapi                        0.8.2
btrfsutil                     5.13
CacheControl                  0.12.6
cached-property               1.5.2
cachy                         0.3.0
caffeine-ng                   3.5.1.post39+gdc71791
ceph                          1.0.0
ceph-volume                   1.0.0
cephfs                        2.0.0
cephfs-shell                  0.0.1
certifi                       2020.12.5
cffi                          1.14.6
cfgv                          3.3.0
chardet                       4.0.0
cleo                          0.7.6
click                         8.0.1
click-log                     0.3.2
click-repl                    0.2.0
clikit                        0.6.2
cloudpickle                   1.6.0
colorama                      0.4.4
commonmark                    0.9.1
configobj                     5.1.0.dev0
constantly                    15.1.0
contextlib2                   0.6.0.post1
cookiecutter                  1.7.3
coverage                      5.5
crashtest                     0.3.1
cryptography                  3.4.7
Cython                        0.29.24
daemonize                     2.5.0
decorator                     5.0.9
defusedxml                    0.7.1
deluge                        2.0.4.dev56
diff-match-patch              20200713
diffoscope                    178
distlib                       0.3.2
distro                        1.5.0
dnspython                     1.16.0
docker                        5.0.0
docker-compose                1.29.2
docker-pycreds                0.4.0
dockerpty                     0.4.1
docopt                        0.6.2
docstring-to-markdown         0.9
docutils                      0.17.1
ecdsa                         0.17.0
Electrum                      4.1.3
entrypoints                   0.3
ewmh                          0.1.6
fido2                         0.9.1
file-magic                    0.4.0
filelock                      3.0.12
flake8                        3.9.2
flake8-bugbear                21.4.3
flake8-comprehensions         3.3.1
flake8-efm                    1.0.1
flake8-import-order           0.18.1
future                        0.18.2
GeoIP                         1.3.2
gpg                           1.16.0
greenlet                      1.1.0
gunicorn                      20.1.0
helpdev                       0.7.1
html5lib                      1.1
humanize                      3.1.0
hyperlink                     21.0.0
hypothesis                    6.14.3
icalendar                     4.0.7
identify                      2.2.11
idna                          3.2
imagesize                     1.2.0
importlib-metadata            4.6.1
incremental                   21.3.0
inflection                    0.5.1
iniconfig                     1.1.1
intervaltree                  3.1.0
ipdb                          0.13.9
ipykernel                     5.5.3
ipython                       7.25.0
ipython-genutils              0.2.0
ipywidgets                    7.6.3
isc                           2.0
isort                         5.8.0
jedi                          0.18.0
jedi-language-server          0.34.1
jeepney                       0.7.0
jellyfish                     0.8.3
Jinja2                        3.0.1
jinja2-time                   0.2.0
jmespath                      0.10.0
jsonrpclib-pelix              0.4.2
jsonschema                    3.2.0
jupyter-client                6.1.12
jupyter-console               6.4.0
jupyter-core                  4.7.1
jupyterlab-pygments           0.1.2
keyring                       23.0.1
khal                          0.10.4.dev6+g4e9fb7c
langdetect                    1.0.9
lark-parser                   0.11.3
lazy-object-proxy             1.6.0
lensfun                       0.3.95
libarchive-c                  3.1
libfdt                        1.6.1
libtorrent                    1.2.14-build-libtorrent-rasterbar-src-libtorrent-rasterbar-1.2.14-bindings-python
libvirt-python                7.3.0
lit                           12.0.1.dev0
lockfile                      0.12.2
louis                         3.18.0
lxml                          4.6.3
Mako                          1.1.4
Markdown                      3.3.4
MarkupSafe                    2.0.1
matplotlib-inline             0.1.2
mccabe                        0.6.1
mercurial                     5.8.1
mistune                       0.8.4
more-itertools                8.8.0
msgpack                       1.0.2
multidict                     5.1.0
mypy                          0.910
mypy-extensions               0.4.3
nbclient                      0.5.3
nbconvert                     6.1.0
nbformat                      5.1.3
nest-asyncio                  1.5.1
nftables                      0.1
nodeenv                       1.6.0
notebook                      6.3.0
notify2                       0.3.1
notmuch                       0.32.2
notmuch2                      0.32.2
numpy                         1.21.1
numpydoc                      1.1.0
oauthlib                      3.1.1
openrazer                     3.0.1
openrazer-daemon              3.0.1
ordered-set                   4.0.2
packaging                     20.9
pandocfilters                 1.4.3
paramiko                      2.7.2
parsedatetime                 2.6
parso                         0.8.2
pastel                        0.2.0
pathspec                      0.9.0
pathtools                     0.1.2
patiencediff                  0.2.2
pbkdf2                        1.3
pep517                        0.11.0
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        8.3.1
pip                           20.3.4
pipenv                        2021.5.29
pkginfo                       1.7.1
platformdirs                  2.0.2
pluggy                        0.13.1
ply                           3.11
poetry                        1.1.7
poetry-core                   1.0.3
poyo                          0.5.0
pre-commit                    2.10.1
progress                      1.5
progressbar2                  3.53.1
prometheus-client             0.10.1
prompt-toolkit                3.0.19
protobuf                      3.17.3
psutil                        5.8.0
ptyprocess                    0.7.0
pulsectl                      21.5.18
pwquality                     1.4.4
py                            1.10.0
pyaes                         1.6.1
pyasn1                        0.4.8
pyasn1-modules                0.2.8
PyBluez                       0.23
pycairo                       1.20.0
pycodestyle                   2.7.0
pycparser                     2.20
pycryptodomex                 3.10.1
pydantic                      1.8.2
pydocstyle                    6.1.1
pyflakes                      2.3.1
pygls                         0.11.1
Pygments                      2.9.0
PyGObject                     3.40.1
pylev                         1.4.0
pylint                        2.7.4
pyls-black                    0.4.6
pyls-spyder                   0.3.2
pymediainfo                   5.1.0
PyNaCl                        1.4.0
pynvim                        0.4.3
pyOpenSSL                     20.0.1
pyparsing                     2.4.7
PyQt5                         5.15.4
PyQt5-sip                     12.9.0
PyQtWebEngine                 5.15.4
pyrsistent                    0.18.0
pyscard                       2.0.0
PySide6                       6.1.2
PySocks                       1.7.1
pytest                        6.2.4
pytest-asyncio                0.15.1
pytest-cov                    2.12.1
pytest-httpserver             1.0.0
python-dateutil               2.8.1
python-dotenv                 0.18.0
python-jsonrpc-server         0.4.0
python-language-server        0.36.2
python-Levenshtein            0.12.2
python-slugify                5.0.2
python-utils                  2.5.6
python-xlib                   0.31
pytz                          2021.1
pyudev                        0.22.0.dev20201112
pyupgrade                     2.21.2
pyxDamerauLevenshtein         1.6.1
pyxdg                         0.27
PyYAML                        5.4.1
pyzmq                         22.1.0
QDarkStyle                    3.0.2
qrcode                        6.1
qstylizer                     0.1.10
QtAwesome                     1.0.2
qtconsole                     5.1.1
QtPy                          1.9.0
rados                         2.0.0
rbd                           2.0.0
Reflector                     2021.7.8.19.52.52
regex                         2021.7.6
rencode                       1.0.6
reorder-python-imports        2.6.0
requests                      2.26.0
requests-toolbelt             0.9.1
resolvelib                    0.5.5
retrying                      1.3.3
rgw                           2.0.0
rope                          0.19.0
rsa                           4.7.2
s3transfer                    0.5.0
SecretStorage                 3.3.1
Send2Trash                    1.7.1
service-identity              21.1.0
setproctitle                  1.2.2
setuptools                    57.4.0
setuptools-scm                6.0.1
shellingham                   1.4.0
shiboken6                     6.1.2
shotman                       0.1.3
six                           1.16.0
snowballstemmer               2.1.0
solaar                        1.0.6
sortedcontainers              2.4.0
speedtest-cli                 2.1.3
Sphinx                        4.1.1
sphinx-rtd-theme              0.5.2
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
spyder                        5.0.1
spyder-kernels                2.0.1
stevedore                     3.3.0
subdownloader                 2.1.0
tabulate                      0.8.9
team                          1.0
termcolor                     1.1.0
terminado                     0.10.1
testpath                      0.4.4
text-unidecode                1.3
textdistance                  4.2.0
texttable                     1.6.4
three-merge                   0.1.1
tinycss                       0.4
tlsh                          0.2.0
todoman                       4.0.0.post2+g1909486
tokenize-rt                   4.0.0
toml                          0.10.2
tomli                         1.0.4
tomlkit                       0.7.2
torbrowser-launcher           0.3.5
tornado                       6.1
tox                           3.24.0
tox-poetry                    0.3.0
traitlets                     5.0.5
trash-cli                     0.21.6.30
trustme                       0.8.0
Twisted                       21.2.0
typed-ast                     1.4.3
typeguard                     2.12.1
typing-extensions             3.10.0.0
tzlocal                       2.1
ujson                         4.0.2
urllib3                       1.26.6
urwid                         2.1.2
validate                      5.1.0.dev0
vdirsyncer                    0.18.1.dev44+g98fcd12
virtualenv                    20.6.0
virtualenv-clone              0.5.5
virtualenvwrapper             4.8.4
watchdog                      0.10.6
wcwidth                       0.2.5
webencodings                  0.5.1
websocket-client              0.59.0
Werkzeug                      2.0.1
wheel                         0.36.2
widgetsnbextension            3.5.1
wrapt                         1.12.1
wurlitzer                     2.0.0
yapf                          0.31.0
yarl                          1.6.3
youtube-dl                    2021.6.6
yubikey-manager               4.0.3
zipp                          3.5.0
zope.interface                5.4.0
```

**Comment by WhyNotHugo** [comment]
Here's a better reproduction example. Since it requires installing something system-wide, I've used docker to isolate this from the host OS:

    docker run --rm -it python:3.9 bash

Inside the container run:

    pip install reorder-python-imports vdirsyncer
    git clone https://github.com/pimutils/vdirsyncer.git
    cd vdirsyncer
    reorder-python-imports vdirsyncer/storage/dav.py
    git diff

(In my case `vdirsyncer` is installed via my distro's package manager, but `sudo pip install` is close enough and reproduces the issue well enough).

**Comment by asottile** [comment]
yeah that makes sense then, you have a global third party installation which will always be discovered first (I would not recommend using global installs **at all**)

next time when making an issue to save us all time please *start* with your reproduction, it would have saved us all hours of time

**Comment by WhyNotHugo** [comment]
> I would not recommend using global installs at all

For applications that are part of the desktop (or even part of the OS itself), this is unavoidable. I'm not using `sudo pip install`; I'm installing it via my OS's package manager. I can't really imagine any reasonable workaround.

Did you mean to close this issue intentionally? Is there any workaround for this?

I think it might make sense to detect if the file being edited is the same one that's in the global third party installation, or would that end up being too slow?

> next time when making an issue to save us all time please start with your reproduction, it would have saved us all hours of time

My bad, I mistakenly assumed the cause was elsewhere, sorry about that!

**Comment by asottile** [comment]
yes, don't use global installs -- the output is correct

**Comment by WhyNotHugo** [comment]
> yes, don't use global installs

I don't really understand what you're trying to propose here. If I remove all global installs, my system won't boot to my desktop any more, aside from all sorts of things breaking pretty badly.

I have `vdirsyncer` installed because I use it on my desktop. I also have 4 other packages installed that depend on `vdirsyncer` (and not all of them are Python packages either). Trying to remove it would result in all dependant packages being removed too, and I rely on them daily.

`vdirsyncer` is only one example of codebases on which I'm having this issue.

Uninstalling it from my system isn't an option. I'm a maintainer _and_ a user of the same product, this can't be such a crazy scenario. Is this issue really a `WONTFIX`?

**Comment by asottile** [comment]
take it up with your operating system packager of `reorder-python-imports` then -- it's working as intended from my point of view

**Comment by WhyNotHugo** [comment]
> take it up with your operating system packager of reorder-python-imports then

That would be me.

> it's working as intended from my point of view

Let me give another example: suppose you want to use `reorder-python-imports` to sort import of [dnf, a package manager](https://github.com/rpm-software-management/dnf), and you're running Fedora (this isn't a crazy idea either: I can imagine Fedora's developers actually use Fedora).

`dnf` is part of the base OS. Removing it is not possible, and if you did manage to remove it, your system would be broken and require a reinstall (or some serious surgery  to get it working again).

Simply "not installing" a package on one's system is not an option, especially since the package may be part of the system.

> it's working as intended from my point of view

Can the "intended behaviour" be discussed so as to accommodate this scenario? I don't think I'm proposing something unreasonable here.

**Comment by asottile** [comment]
you're not understanding -- I'm not asking you to remove `dnf`, I'm asking you to use `reorder-python-imports` from your virtualenv

**Comment by WhyNotHugo** [comment]
I _was_ misunderstanding actually. :+1: 

So installing `reorder-python-imports` itself as a global install is what's unsupported? How would you advise a system package to install this? Using a dedicated virtualenv?

**Comment by asottile** [comment]
it's not that it's unsupported -- it's that when you've got a global package it's going to be identified as such:

```pycon
>>> import ufw
>>> ufw.__file__
'/usr/lib/python3/dist-packages/ufw/__init__.py'
>>> from aspy.refactor_imports.classify import classify_import
>>> classify_import('ufw')
'THIRD_PARTY'
```

as aside: I don't recommend operating systems to try to package my things because they often don't understand the software that they are packaging and waste copious amounts of my time on problems that exist between their keyboard and their chair.

**Comment by WhyNotHugo** [comment]
I've been asking politely, and I'd appreciate if you can abstain from insults.

> it's not that it's unsupported -- it's that when you've got a global package it's going to be identified as such

I don't think I understand this bit. If installed globally it gives erroneous results, but it's **not** unsupported? I was thinking it'd be safer to add a note in the README stating that global installs are discouraged given they may result in misidentifying packages.

> I don't recommend operating systems to try to package my things

Packaging tools is what allows us developers to install them. How do you envision this should happen? For example, I install `reorder_python_imports` since I've `nvim` configured to use it under the hood to reorder imports.

**Comment by asottile** [comment]
first off, the insult is not intended towards you -- there's even lower quality reports that are frequent from a certain few packagers.  and when people fork / patch / install in weird layouts / etc. and then report bugs because of their mistakes it's a huge waste of time for everyone involved -- install it from `pip` using `pip` avoids the entire class of problems

I guess I'm just frustrated with this issue because you started with a very low quality vague "it's not working" with no reproduction report. it then took me **three rounds of asking for a reproduction** for you to tell me that your original report was factually incorrect and that you're instead globally installing everything!

I avoid the system python like the plague, especially for reasons similar to this one.  it's way too easy for packages to have bad interactions with each other *or* for the operating system packager to make a poor decision about how things are packaged.  it's fairly easy to set up a virtualenv and install tools there -- that's [how I avoid this mess entirely](https://youtu.be/O390_abzo08)

the results are not erroneous, it is installed as a third party package and presented to the import system as a third party package so it is identified as such

**Comment by WhyNotHugo** [comment]
Regarding packagers shipping forks, and alike, I can, regrettably, relate to that. `vdirsyncer` itself has a history of distributions shipping a fork of an old version, and users continuously having issues with "the latest version". [That's also one of the biggest reasons for the former maintainer to step down](https://github.com/pimutils/vdirsyncer/issues/790#issue-421926278).

OHOT, I do apologise about the lack of repro steps. It happens to me on so many projects that I had a hard time pinpointing down all the relevant factors.

---

Oh the topic of system packages: I guess choice of distribution is key on this item. Arch has a strong policy of following upstream defaults and not applying patches, so the experiences tends to be a bit different. Versions are updated pretty fast, but also made sure to work with one another.

I'm really not sure how I'd deal with installing this _without_ it being a system package. For one, when I install a new system (physical or not), I merely re-install the same system packages, dotfiles and that's it. It seems that I'd now require an extra step for one single package: `reorder_python_imports`, but I'm also unsure what those steps should be.

Installing it in a dedicated virtualenv suddenly puts the burden of manually updating it on each system, which really doesn't scale. It'd also break every time there's a major python update. Not a huge deal, but I'd rather not have such a snowflake requiring such attention.

How do _you_ install `reorder-python-imports`?

**Comment by asottile** [comment]
I don't, I only use it through `pre-commit`
