### ISSUE TITLE
Wrong order of Third and First Party imports

### ISSUE THREAD

**Issue by MagunRa** [asottile/reorder_python_imports#190]
Hi,
reorder-python-imports sorts both first and third party imports in one block. In this block the imports are sorted alphabetically.

e.g. after reorder:
```
from afirstparty import stuff
from bthirdparty import stuff
```

But I would expect it to be:
```
from bthirdparty import stuff

from afirstparty import stuff
```

I have no idea what causes this behavior.

**Comment by asottile** [comment]
I can't see your screen, please provide a reproduction.  without looking my best guess is you have a src layout and have not read the README

**Comment by MagunRa** [comment]
I have read it but carefully enough.
Thank you.
