### ISSUE TITLE
Debugging option

### ISSUE THREAD

**Issue by verhovsky** [asottile/reorder_python_imports#193]
We use reorder_python_imports at work through pre-commit. Today one of the developers said it started re-ordering pip installed dependencies as 3rd party dependencies, so

```py
import os

import numpy as np

import an_internal_library.some_func
```

is being re-ordered as

```py
import os

import an_internal_library.some_func
import numpy as np
```

I would like a `--debug` option that I could tell him to add to `.pre-commit-config.yaml` that would print out the internal state of reorder_python_imports (and the path of the python its running under?) so that I could have some information about why it could be breaking on his machine to help debug this issue. As it stands, I don't really have much to go on.

**Comment by asottile** [comment]
the most likely scenario is they have `./an_internal_library` -- reorder-python-imports doesn't actually keep any state here beyond what you see in the output -- the main classification functionality comes from [aspy.refactor_imports](https://github.com/asottile/aspy.refactor_imports)

p.s. your work should probably sponsor if they're using software ;)

**Comment by verhovsky** [comment]
> they have `./an_internal_library`

yea, we do. It should be ordered separately from `numpy`. We don't have a ./numpy.

> your work should probably sponsor

I agree, *I* sponsor you to try to make up for it :)

**Comment by asottile** [comment]
<3

so it's unclear whether reorder-python-imports thinks they're both third party or both first party from that -- maybe play around with `classify` in an isolated virtualenv and see if it makes any difference?

**Comment by verhovsky** [comment]
Thank you for the suggestion to mess around with `classify_import` directly, that was the real answer. It turns out it's because we have symlinks and the order in `--application_directories` matters. Here's a minimal viable example of what was happening on his machine:

```sh
tmp$ cd /tmp
tmp$ mkdir reorder_test
tmp$ mkdir reorder_test/mymod
tmp$ touch reorder_test/mymod/__init__.py
tmp$ python
Python 3.9.6 (default, Jun 28 2021, 19:24:41) 
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from aspy.refactor_imports.classify import classify_import
>>> classify_import('mymod')
'THIRD_PARTY'
>>> classify_import('mymod', ('reorder_test',))
'APPLICATION'
>>> 
tmp$ mv reorder_test reorder_test_not_symlink
tmp$ ln -s /tmp/reorder_test_not_symlink/ /tmp/reorder_test
tmp$ python
Python 3.9.6 (default, Jun 28 2021, 19:24:41) 
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from aspy.refactor_imports.classify import classify_import
>>> classify_import('mymod', ('reorder_test',))
'THIRD_PARTY'
>>> classify_import('mymod', ('reorder_test_not_symlink',))
'APPLICATION'
>>> classify_import('mymod', ('reorder_test', 'reorder_test_not_symlink',))
'THIRD_PARTY'
>>> classify_import('mymod', ('reorder_test_not_symlink', 'reorder_test'))
'APPLICATION'
>>> 
```

Basically, on my machine my code is in `/some/dir`, on his it's in `/some_other/dir` and `/some/dir` is a symlink to `/some_other/dir` and we had `--application-directories=/some/dir:/some_other/dir` and that causes `classify` to mis-classify everything in `/some_other/dir` as THIRD_PARTY. In reality his symlink situation is more complicated and `/some_other/dir` goes through a chain of like 3 symlinks but I don't think that matters. Since on my machine I don't have `/some_other/dir` at all, we just swapped it around to `--application-directories=/some_other/dir:/some/dir` and it seems to work for both of us.
