### ISSUE TITLE
Ignore a folder(s)

### ISSUE THREAD

**Issue by alanwill** [asottile/reorder_python_imports#204]
I spent some time trying to figure this out but can't. I can see how to ignore lines in a file but is there a way to ignore folders altogether? In my repo I have a few external libraries which I don't want linted. How can I ignore them altogether?

**Comment by asottile** [comment]
[`exclude`](https://pre-commit.com/#config-exclude)

**Comment by alanwill** [comment]
Omg thank you! 😊
