### ISSUE TITLE
Remove unused imports?

### ISSUE THREAD

**Issue by jyotirmay123** [asottile/reorder_python_imports#207]
Is it possible to auto remove unused imports in the python file removed, using this hook?

if so how and if not, can it be added as a feature request?

For ex:

```python
    import json
    import simplejson

    json.dumps({"key": "value"})

```

should become

```python
    import json

    json.dumps({"key": "value"})

```

Best,

**Comment by Agent-Hellboy** [comment]
But it must be with a flag like `--remove unused imports` right?
for example
```.
├── __init__.py
├── pkg.py
└── subpkg
    ├── a.py
    ├── b.py
    └── __init__.py
```
we can leave unused imports like `from .a import a_func` in the `__init__.py` file of `subpkg` and later use those in `pkg.py` as `from .subpkg import a`

**Comment by jyotirmay123** [comment]
@Agent-Hellboy Nice scenario, yes in this case, we have to ignore removing unused imports, but in normal scenario, it would be nice to have a way to remove unused imports. and yes with the support of a flag like `--remove_unused_imports` or so.

**Comment by asottile** [comment]
unused detection is difficult so it is not currently attempted

and sometimes people import things intentionally for the side effects even though it's a bad idea

**Comment by Agent-Hellboy** [comment]
>>>unused detection is difficult so it is not currently attempted
I attempted here https://github.com/Agent-Hellboy/find-unused-import
Hopes you will review it and give suggestions to me for improvement

**Comment by asottile** [comment]
@Agent-Hellboy while I appreciate the comment -- an issue tracker isn't here for you to advertise, thanks
