### ISSUE TITLE
Selectively preventing removed duplicates

### ISSUE THREAD

**Issue by tomasgareau** [asottile/reorder_python_imports#221]
I've been running some zmq asyncio examples something like this:

```python
import asyncio
import zmq
import zmq.asyncio

ctx = zmq.asyncio.Context()

# ... later

socket = ctx.socket(zmq.PUSH)
```

`reorder_python_imports` removes the `zmq` import since we're also importing a submodule of it (`zmq.asyncio`).

```python
import asyncio
# import zmq -- now gone
import zmq.asyncio

ctx = zmq.asyncio.Context()
socket = ctx.socket(zmq.PUSH)
```

Though this doesn't cause any runtime changes, it causes my type checker (Pyright) to complain that `zmq.PUSH` is not defined. I [checked with Pyright](https://github.com/microsoft/pyright/issues/2964) and this is their intended behaviour. They don't want to encourage/support cross-module implicit initialization and suggest either:
* importing the submodule (in my case, `from zmq import asyncio` will shadow `asyncio`, which I don't want)
* importing the required symbols directly (in my case, `from zmq.asyncio import Context` -- this would work but I like the "namespacing" of `zmq.asyncio.Context`)

All-in-all, this is a pretty minor issue for me with pretty easy workarounds but I wanted to know either:
* if there's a way to prevent the removal of `import zmq` in this scenario or,
* if you have another recommended approach here

**Comment by asottile** [comment]
sorry no -- pyright is not doing the correct thing here.  they should make their checker compliant with python
