### ISSUE TITLE
unclear import order for `from safer import open`

### ISSUE THREAD

**Issue by jhereth** [asottile/reorder_python_imports#222]
Hi,

the statement `from safer import open` is interpreted as stdlib when running the hook inside a venv with installed `safer`. If running in an isolated environment, it appears as third party library import.

Which one is correct? (I think the latter)

You can find a gist with an example [here](https://gist.github.com/jhereth/3408cf7997871da9609f5afe6bdfdd5c).

Background: I discovered this when debugging similar behavior in a [hypermodern python](https://github.com/cjolowicz/hypermodern-python) setup where this line would switch positions when running with nox vs calling the hook via `pre-commit` without nox.

Is there a way to make reorder-python-imports more stable?

**Comment by asottile** [comment]
I cannot reproduce:

```python
>>> import aspy.refactor_imports.classify
>>> aspy.refactor_imports.classify.
>>> aspy.refactor_imports.classify.classify_import('safer')
'THIRD_PARTY'
```

**Comment by asottile** [comment]
I suspect you're actually confusing the classification of `pathlib` and you're running an ancient version of python

**Comment by jhereth** [comment]
That ancient version would be `3.10.2`.

While classification works correctly, the output of `reorder-python-imports` changes if `safer` is installed.

See [here](https://gist.github.com/jhereth/e3bc6aa6c6451fce2ba1e89a70b41f4f):

1. output of `reorder-python-imports` is correct (line 23)
2. after installing `safer` (line 29) it is wrong (line 38)
3. classification is still `THIRD_PARTY` (line 49)

**Comment by asottile** [comment]
ah, it seems safer erroneously installs its module into `bin/` -- so it's on `sys.path` when you run a bin script -- [safer should not do that](https://github.com/rec/safer/blob/85c53f9d0502a6a2410741b3b662ea8ad73cff2e/setup.py#L32)

**Comment by jhereth** [comment]
If this is wrong, I could open an issue there. Do you have any reference why not to do this? The [docs](https://docs.python.org/3/distutils/setupscript.html#installing-scripts) seem not to mention any restriction in this regard.

(not sure I understand why this overrides the classification though)

**Comment by asottile** [comment]
well if you try and run `safer.py` on your terminal you'll see that it's not actually a valid script.  `scripts` are fine, but `safer.py` is not a script

it ends up on `sys.path` due to the way python handles scripts, placing the directory of the script on the beginning of `sys.path`

**Comment by asottile** [comment]
(compare with `python -m reorder_python_imports`)

**Comment by jhereth** [comment]
Thanks, @rec just pushed the [fix](https://github.com/rec/safer/pull/17).
