### ISSUE TITLE
Gracefully handle try, except blocks in imports

### ISSUE THREAD

**Issue by MLNW** [asottile/reorder_python_imports#241]
I have a class where I am unsure at runtime if a specific module is going to be available. To avoid failing I, therefore, have to wrap the import with a `try, except` block. Once I add this block the remaining imports are no longer reordered. The `reorder-python-imports` script does not print anything when called on such a file.

It would be great if the sorting of the remaining imports continues to work. See below for a concrete example:

[src/dagos/components/git/cli.py](https://github.com/DAG-OS/dagos/blob/e2b2be8ad5652bed43087990766ee414e9ed49d2/src/dagos/components/git/cli.py)
```python
import typing as t
from pathlib import Path


try:
    import ansible_runner
except ImportError:
    pass

import yaml
from loguru import logger

from dagos.platform import PlatformSupportChecker          # <<<< Should be sorted to bottom
from dagos.core.commands import ConfigureCommand
from dagos.core.commands import InstallCommand
from dagos.core.components import SoftwareComponent
from dagos.platform import PlatformIssue
```

**Comment by asottile** [comment]
as soon as there is non-import code `reorder-python-imports` will stop processing the file as it usually indicates that it is order dependent

you can move your non-import code after imports

**Comment by asottile** [comment]
this is [documented](https://github.com/asottile/reorder_python_imports#using--noreorder)

**Comment by MLNW** [comment]
Sorry, obviously a case of RTFM on my part.
