### ISSUE TITLE
multiline import from same package?

### ISSUE THREAD

**Issue by karmingc** [asottile/reorder_python_imports#243]
Hello,

given
```
from typing import Any
from typing import Dict
from typing import List
```

would it be possible that it turns into
```
from typing import (
    Any,
    Dict,
    List
)
```

I believe the proposed approach would be free from any merge conflicts as well. Anything I might not be taking into consideration that could raise any possible issues?

**Comment by asottile** [comment]
several things:

- there is no negotiation of style, reorder-python-imports does this one way with no options
- linter ignore ignore comments wouldn't be placeable on individual imports
- you would still incur conflicts and corrupt blame when going between single line and multiline "styles"

**Comment by karmingc** [comment]
appreciate the response @asottile
