### ISSUE TITLE
Option to disable reordering

### ISSUE THREAD

**Issue by JeppeKlitgaard** [asottile/reorder_python_imports#246]
Thanks for another fantastic hook to improve idiomaticity!

I would really like to be able to use `reorder_python_imports` without the actual reordering. That is, I'd like access to the logic that removes old `__future__`s and `typing_extension`s without having to conform to the more controversial import style imposed by `reorder_python_imports`.

It would be fantastic if the reordering could be disabled with a flag along the lines of `--no-reorder`

**Comment by asottile** [comment]
you can't be seriously suggesting `reorder-python-imports --no-reorder` ?

**Comment by JeppeKlitgaard** [comment]
@asottile I was – no ill intent I assure you, although I would agree that it seems a little silly on the surface.

This stems from a previous discussion in [pyupgrade](https://github.com/asottile/pyupgrade/issues/616). I guess the alternative is waiting for the import upgrade related logic to be added to `pyupgrade`, which I am happy with as well.
