### ISSUE TITLE
Sylink dirs treated as 3rd party modules

### ISSUE THREAD

**Issue by mangelozzi** [asottile/reorder_python_imports#253]
Say one has this project structure:

```
src/
  - foomod/
          - __init_.py
          - foo.py
  - barmod/    # <-- a symlink to else where
          - __init_.py
          - bar.py
  - __init__.py
  - main.py
```
If inside main.py one has (before re-ordering)
```
from django.conf import settings
from foomod.foo import my_func1
from barmod.bar import my_func2
```

Then after ordering one has (with `reorder-python-imports --application-directories=/some/path/to/src`):
```
from barmod.bar import my_func2
from django.conf import settings

from foomod.foo import my_func1
```

Whereas I was expecting:
```
from django.conf import settings

from barmod.bar import my_func2
from foomod.foo import my_func1
```

My guess is maybe because `barmod` is a symlink it thinks its a third party module?

Note: The symlink was created with linux: `ln -s $source $target`

**Comment by asottile** [comment]
wouldn't that by definition make them "third party" since you're "installing" them separately as plugins?

there's also established practices for making python plugins -- perhaps follow one of those such as [entry-points based plugins](https://youtu.be/fY3Y_xPKWNA)

**Comment by mangelozzi** [comment]
> wouldn't that by definition make them "third party" since you're "installing" them separately as plugins?
> 
> there's also established practices for making python plugins -- perhaps follow one of those such as [entry-points based plugins](https://youtu.be/fY3Y_xPKWNA)

Thank you for the video, I watched it. I did not know about entry-points based plugins before. I can't say I understood all of it, but I don't think entry points plugin system is a good fit for my situation. To give more context... 

The framework I am working on sits above Django. Django has its own way of searching through `Django apps` and plugging in various `apps`. In my case theres basically a `core/` and a `dist/` dir which contain django apps (the `dist/` dir contains the symlinked dir). The meat of the distribution I work on is in the `dist/` dir. Things in `core/` are like a common menu system, and various other web helper tools. Inside `dist/` there is a `Django app` called `plug` which tells the framework how to use the `dist/`. But all the apps in `dist/` are the meat of the distribution I work on, but because its symlinked it appears as third party modules.

Each distribution in my eyes is a stand alone release, that happen to share some common code. It was just surprising/unexpected to me that `reorder-python-imports` treats modules differently depending on how they are stored on ones harddrive.

Like if you were deving on a flash stick between two computers and symlinking a dev folder while working on a project, then its treated differently.

If I made a PR to add an option to disable treating symlinks as third part would you accept it?

**Comment by asottile** [comment]
> The framework I am working on sits above Django ...

yeah I strongly suspect you're reinventing the wheel here and that a standard plugin mechanism would work fine and would be less surprising to your users and plugin authors.

> Each distribution in my eyes is a stand alone release, 

yes, that would make them "third party"

> If I made a PR to add an option to disable treating symlinks as third part would you accept it?

no I would not

**Comment by mangelozzi** [comment]
> > The framework I am working on sits above Django ...
> 
> yeah I strongly suspect you're reinventing the wheel here and that a standard plugin mechanism would work fine and would be less surprising to your users and plugin authors.
> 
> > Each distribution in my eyes is a stand alone release,
> 
> yes, that would make them "third party"
Well when I work on the stand alone release, it treat it as third party, instead of first part, thats the problem.

> 
> > If I made a PR to add an option to disable treating symlinks as third part would you accept it?
> 
> no I would not

Well I am trying to work with the Django plug in system (not revinent the wheel), and all that is required is a single simple symbolic link, no code, doesnt get much simpler than that. Anyways at least you made it clear you are not open to it. I found `isort` that supports symbolic links without strong opinions. Thanks for the good communication, cheers!
