### ISSUE TITLE
Option to disable import replacement

### ISSUE THREAD

**Issue by agronholm** [asottile/reorder_python_imports#297]
The `typing_extensions` library contains more up to date versions of some functions and should not be replaced with the corresponding stdlib import. But as the tool cannot know when I actually need these newer versions, there should preferably be an option to prevent the replacement of imports, much like with `# noreorder`.

A practical example, one I ran into, is the `get_type_hints()` function which provides the `include_extras` parameter not found in the stdlib version.

**Comment by asottile** [comment]
in such cases we usually update the target version instead -- for example #289

feel free to send a patch
