### ISSUE TITLE
triple-quoted docstring with trailing backslash silently prevents reordering

### ISSUE THREAD

**Issue by benbariteau** [asottile/reorder_python_imports#304]
I recognize this is extremely specific and easy to remedy, but it's also very hard to diagnose. So at minimum this bug report can serve as documentation for people in the future.

In order to reproduce this you can use this minimal file to test against:
```
"""
foo\
bar
"""
import itertools
import functools
```

If you save this file to foo.py and run `reorder-python-imports foo.py`, it will do nothing. Instead, it _should_ reorder `import functools` to be above `import itertools`.

There's a further weirdness which is that if you use `--add-import`, it will add that import _above_ the docstring. So if you run `reorder-python-imports --add-import 'import functools'` on the above file, you'll get:
```
import functools
"""
foo\
bar
"""
import itertools
import functools
```

**Comment by asottile** [comment]
which version are you using? there was a bug with docstring parsing that got fixed at some point

**Comment by benbariteau** [comment]
> which version are you using? there was a bug with docstring parsing that got fixed at some point

This is on 3.8.4, the latest
