### ISSUE TITLE
Removes blank lines between comments

### ISSUE THREAD

**Issue by sckarlin** [asottile/reorder_python_imports#314]
In the, admittedly unusual, case of a python file like this:
```python
# comment line 1

# comment line 3

# comment line 5
```
Using `pre-commit` with `reorder-python-imports` transforms the file to:
```python
# comment line 1
# comment line 3
# comment line 5
```
Since there are no imports in the file, my expectation is that the file would be untouched.

Details:
* Using a Python 3.11.0 virtual environment
* git version 2.38.1
* pre-commit 2.20.0
* reorder-python-imports 3.9.0 with --py310-plus

Example script:
```bash
mkdir Temp
cd Temp
python3.11 -m venv venv

cat >foo.py << EOF
# comment line 1

# comment line 3

# comment line 5
EOF

cat >.pre-commit-config.yaml << EOF
repos:
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    -   id: reorder-python-imports
        args: [--py310-plus]
EOF

git init .
venv/bin/python -m pip install pre-commit==2.20.0
venv/bin/pre-commit install
git add foo.py
git commit -m "Initial Commit"
```
At this point, the even numbered lines between the comments are removed.

**Comment by asottile** [comment]
please search the issue tracker next time #66

**Comment by sckarlin** [comment]
Dang!  I searched the *open* issues but not the closed issues.  My bad.
And this is even after recently watching https://www.youtube.com/watch?v=cGYVGVsXNFM
Thanks for a great tool.
