### ISSUE TITLE
Relative import ordering

### ISSUE THREAD

**Issue by tolomea** [asottile/reorder_python_imports#322]
I'm looking at moving over from isort, my only point of friction is relative imports.

I know they are a topic where a lot of people have strong opinions.
Our house style uses flake8-tidy-imports to limit them to same package only, we find that for same package relative is lower cognitive load than absolute, while cross package it's more cognitive load.

I see from comments and issues that you don't personally use relative imports and that having them in their own section like isort does caused a bunch of issues.

It looks like changing the sort order to place relatives last was maybe also a feature at some point although without release notes I'm not sure if/when/why, it's quite hard to tell from the git log of classify-imports.

How do you feel about changing the sort key so that relatives get placed after absolute imports rather than before?

As an unconditional behaviour it looks like it'd be maybe a half dozen lines + tests.
Obviously conditional would be a lot more work, however it seems unlikely that anyone using relative imports particularly expects them to be first.

**Comment by tolomea** [comment]
I should add that I'm happy to have a crack at a PR, just given the history I'd like to check first if it's going to get a flat no response. And if not how you feel about the optional vs always question.

**Comment by asottile** [comment]
no thanks -- the whole point of the tool is there's no bikeshedding.  it does one thing and only one thing.  isort for example has a fractal of options which makes it impossible to agree on a style

**Comment by tolomea** [comment]
ok, but what about as unconditional, which would be my suggested option anyway.

**Comment by tolomea** [comment]
I strongly agree with limited options, I like black for that as well.

**Comment by asottile** [comment]
it already is unconditional?

**Comment by tolomea** [comment]
I mean always sort relative imports after absolute ones. Don't provide an option, change the opinionated style.

**Comment by tolomea** [comment]
Within the existing blocks, so just a couple of lines change to each of the sort_key functions. The number field at the front that's used for distinguishing from imports could be extended to have a couple more values for relative and from relative.

**Comment by tolomea** [comment]
A new value for relative, there isn't a `import .bob`, clearly time for me to go home for the evening.

**Comment by asottile** [comment]
see now you're bikeshedding the style

**Comment by tolomea** [comment]
I viewed it as suggesting an improvement to a bit of the style that afaik you don't personally care about.
