### ISSUE TITLE
add-import with module without imports

### ISSUE THREAD

**Issue by HeySlava** [asottile/reorder_python_imports#327]
Hello. Is it correct behavior?

```python3
# module.py
def foo():
    pass
```
if I run `reorder-python-imports --add-import 'from __future__ import annotations' module.py`

The result will be:
```python3
from __future__ import annotations
def foo():
    pass
```

I expect empty line between import and def foo()

I know it's a weird example, but I have met it when run with pre-commit.

**Comment by asottile** [comment]
yes
