### ISSUE TITLE
Adding prober ignore files

### ISSUE THREAD

**Issue by felixnext** [asottile/reorder_python_imports#330]
It would be great to have proper ignore option (not just `#no-reorder`), since there might be auto-generated files that should not be reordered (e.g. protobuf files).

Proposed design is either to provide a list of regex patterns to exclude (that can also be passed in the pre-commit hook) or specify an ini file in root folder (similar to `pyproject.toml` for black) that would allow to specify the ignore patterns.

**Comment by asottile** [comment]
no thanks
