### ISSUE TITLE
can you please add the lxml library.

### ISSUE THREAD

**Issue by mimo-404nf** [asottile/reorder_python_imports#331]
when I am using the pre commit it orders the local import before the lxml import which cause pylint error could you please fix this issue.

Thanks

**Comment by asottile** [comment]
you're going to have to provide more information to reproduce the problem

this isn't a problem with this tool -- it's something you've done

**Comment by mimo-404nf** [comment]
I have my mypackage 
and i am importing like so :

from lxml import etree
from mypackage import module

when i run the pre-commit it reorder them   like so : 

from mypackage import module
from lxml import etree

**Comment by mimo-404nf** [comment]
|_ src
    |_ mypackage
          |_utils.py
          |_ main_class.py
          |_ modules
              |_ submodule.py
              |_init__.py


in the submodule I am importing like so:

from lxml import etree
from mypackage.main_class import MyClass


when I use pre-commit run --all-files

the new imports order is like so:

from mypackage.main_class import MyClass
from lxml import etree

**Comment by asottile** [comment]
have you read the readme? it addresses your problem

**Comment by mimo-404nf** [comment]
what I'm mentioning that it order them in the wrong order the lxml shoud be before my local imports,
not after.

**Comment by mimo-404nf** [comment]
Thsnks for your respond anyway, really appreciate it.

**Comment by asottile** [comment]
yeah you've missed an important part of the README due to your directory structure

**Comment by mimo-404nf** [comment]
aw thanks man really sorry I just added my application-dir and it's working perfectly.
sorry, my mistake.
