### ISSUE TITLE
Support STDIN/STDOUT

### ISSUE THREAD

**Issue by alok** [asottile/reorder_python_imports#37]
If there was a flag like `--stdout` to output the changed text to STDOUT, that would be nice.

Being able to read from STDIN would make it perfect for autoformatters like [neoformat](https://github.com/sbdchd/neoformat).

**Comment by asottile** [comment]
I believe you're looking for `--print-only`?

**Comment by Alok** [comment]
My bad. Does this support reading STDIN as well (afk, so I can't check right now)

**Comment by asottile** [comment]
`reorder-python-imports /dev/stdin --print-only` should work:

```
$ echo -e 'import os\nimport pre_commit\nimport sys' | reorder-python-imports /dev/stdin --print-only
==> /dev/stdin <==
import os
import sys

import pre_commit
```

**Comment by asottile** [comment]
(note that the `==> /dev/stdin <==` output goes to stderr)

**Comment by asottile** [comment]
closing: if `--print-only` doesn't satisfy your usecase please provide additional context and I'll reopen :)

**Comment by alok** [comment]
Sorry, forgot about this. It needs to output specifically to STDOUT rather than STDERR since most editor formatter plugins only read STDOUT. Plus, it's not really an *error* as such, so it shouldn't be redirected there.

**Comment by asottile** [comment]
it does, you haven't tried it have you :P

**Comment by alok** [comment]
You're right, I didn't. I misread the sentence "(note that the `==> /dev/stdin <==` output goes to stderr)". I thought you meant *all* of it was redirected to STDERR rather than just that literal line. My bad.

**Comment by alok** [comment]
On the other hand, I don't think Windows supports `/dev/stdin`. I don't use Windows, but I'd expect other people do.

**Comment by asottile** [comment]
If someone on windows wants the feature then we'll talk -- as it is it hasn't been an ask so far and if I'm not going to use it and you're not going to use it there's no point in complicating this tool

**Comment by pmiddend** [comment]
I'm trying to implement emacs support for this fine tool. This would be a little easier if `--print-only` _always_ printed the result, whether there was a reordering or not. Is that possible?
