### ISSUE TITLE
Add check mode

### ISSUE THREAD

**Issue by davidism** [asottile/reorder_python_imports#45]
I'd like to run this during testing to ensure PRs follow the format. A `--check` option could do `sys.exit(1)` if any reformatting would be performed.

**Comment by asottile** [comment]
I believe `--diff-only` satisfies this requirement and is already implemented.

Though I'd suggest execution via [pre-commit](https://pre-commit.com) where you can just use `pre-commit run --all-files --show-diff-on-failure` in CI

**Comment by asottile** [comment]
Ah shoot, I might have typo'd that (on mobile) adjust spacing where appropriate :D

**Comment by davidism** [comment]
Thanks, those both work. Didn't realize pre-commit could do that!

**Comment by asottile** [comment]
Thanks for the issue :D
