### ISSUE TITLE
Add --show-diff flag

### ISSUE THREAD

**Issue by Dinoshauer** [asottile/reorder_python_imports#5]
Hey there, a ``--show-diff`` option (or, another non-modifying way) of running ``reorder-python-imports`` would be really nice to have. It's really the only request I have for this, I didn't use the other parameters in ``isort``.

I will be referencing your repo on https://github.com/FalconSocial/pre-commit-python-sorter to redirect people here as this doesn't have the same PATH requirements as ``isort`` does.

**Comment by asottile** [comment]
aww dangit, teach me to refresh more often >.< looks like we both implemented this

**Comment by Dinoshauer** [comment]
Haha, oh dear!
