### ISSUE TITLE
Hook removes blank lines not related to imports at all

### ISSUE THREAD

**Issue by IvanBoyko** [asottile/reorder_python_imports#66]
Fantastic tool, however below is probably a bug.

Hook removes **blank lines**, that are not related to imports at all.

Example python script (notice blank lines around docstring):
```
$ cat test.py 
#!/usr/bin/env python3

"""
Here goes synopsis
"""

import os
import random
import time

print("asdf")
```

Here is my *pre-commit* config:
```
$ cat .pre-commit-config.yaml 
repos:
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.3.5
    hooks:
    -   id: reorder-python-imports
        language_version: python3
```

Here is the run of the hook:
```
$ pre-commit run reorder-python-imports
Reorder python imports...................................................Failed
hookid: reorder-python-imports

Files were modified by this hook. Additional output:

Reordering imports in test.py
```

And the result:
```
$ cat test.py 
#!/usr/bin/env python3
"""
Here goes synopsis
"""
import os
import random
import time

print("asdf")
```

**Comment by asottile** [comment]
This is ~kinda intentional.  the hook manages all newlines from the beginning of the file to the first "non-import / non-docstring code" portion.  Is this a problem?

**Comment by IvanBoyko** [comment]
Well, it ±kinda is :)
I love having a blank line after shebang at least.  
I'm fairly new to Python, so not sure if this is against any PEP8 or other conventions \ style rules.

Even if it is, it still feels that blank lines before all the imports or after them - should not be the concern of the **reorder-python-imports** check.

**Comment by asottile** [comment]
pep8 doesn't really care either way.

Part of reordering is separating the imports into sections -- in order to do that accurately reorder-python-imports needs control of all the whitespace.  It would be _possible_ to maintain it, but a lot more complicated.  Plus you'd lose out on this fix:

```diff
 """docstring"""
-
-
-
 import os
```

Another design principle at play here is "consistency > configuration" -- along the same lines of "only one way to do it".  reorder-python-imports does this by always normalizing the section it formats to the same output.

Note that after any imports, the whitespace isn't modified, so if you wanted to do something like this (violates pep8):

```python
import os
import sys
x = 1
```

or this:

```python
import os
import sys



x = 1
```

you're more than welcome to

**Comment by IvanBoyko** [comment]
> Plus you'd lose out on this fix ...

Well, in my view it's not a fix - I'd rather have a blank line **before** the very first import, and I don't treat it as part of the imports block.

> always normalizing the section it formats to the same output

I think idempotence here is orthogonal to removing (or not) blank lines before the import block.

**Comment by asottile** [comment]
anyway, I've explained how it is, and why it is, and what it could be, and why it probably won't be.  I don't think there's anything left to discuss here.  If you can make a tested patch which isn't terribly complicated I'd consider it -- but I'm not going to work on it myself because I prefer what happens right now.

**Comment by peterjc** [comment]
@asottile would you consider a pull request for this (as stated in Feb 2019), or did you change your mind (as implied in the Aug 2019 comment)?

I would like ``reorder_python_imports`` to preserve all lines before the first import, just like it preserves all lines after the imports. I was about to log a duplicate issue until GitHub pointed me here.

Example input (with ``import sys`` before ``import os``):

```python
#!/usr/bin/env python
# Copyright 2020 Peter Cock.
# Released under the MIT Licence

"""This is a short example Python script.

This multiline string defined inside triple quotes is considered
to be the module's docstring.
"""

import sys
import os

sys.stderr.write(f"This is {os.uname().sysname}, aka {sys.platform}\n")
```

Example output from v1.5.1 (import order fixed, but also less blank lines):

```python
#!/usr/bin/env python
# Copyright 2020 Peter Cock.
# Released under the MIT Licence
"""This is a short example Python script.

This multiline string defined inside triple quotes is considered
to be the module's docstring.
"""
import os
import sys

sys.stderr.write(f"This is {os.uname().sysname}, aka {sys.platform}\n")
```

I've seen enough real world Python code from other people to want to leave any blank lines before the first import alone. They can be purely cosmetic as in this example, but I have often seen loads of script documentation done as comment lines where blank lines were deliberate aids to readability.

**Comment by asottile** [comment]
I mean, I have my doubts that a simple patch can accomplish that -- and I don't want an option -- and in your example the copyright / mit license lines aren't necessary (that's what the `LICENSE` file is for, MIT does not require a header -- but sure you'd do that for apache2)

there has to be "one correct way" and currently that's to remove it all
