### ISSUE TITLE
--replace-import should support non-from imports

### ISSUE THREAD

**Issue by firba1** [asottile/reorder_python_imports#67]
The readme says that it doesn't support this, not why exactly.

**Comment by asottile** [comment]
rewriting `import`-imports would change the symbol name which would require either `as` or rewrites throughout the file -- both of which are not great

```diff
-import Queue
+import queue as Queue
```

for instance

**Comment by firba1** [comment]
I think in terms of utility this is worth it. One other caveat I thought of though is a situation like this:
```
import foo.bar
```
with `--replace-import foo.bar=baz.bar` would probably end up with

```diff
-import foo.bar
+import baz.bar
```
But if there was a usage of `foo` later in the file, this would break it. You'd probably have to something like this:
```diff
-import foo.bar
+import foo
+import baz.bar
```
which opens a whole other can of worms.

**Comment by firba1** [comment]
We could support it for single level imports, e.g. `--replace-import foo=bar.foo` would always be safe. idk if "only can rewrite 'import foo' but not 'import foo.bar'" is too surprising?

**Comment by asottile** [comment]
ah yes that was the other reason -- making this not feasible.  the only safe rewrites are `from` imports

**Comment by firba1** [comment]
Yeah that seems unreasonably infeasible and/or surprising. Cool, well at least I know now lol.
