### ISSUE TITLE
--replace-import should support rewriting modules with different symbol names

### ISSUE THREAD

**Issue by firba1** [asottile/reorder_python_imports#68]
This should be as simple as adding an `as` clause?

**Comment by asottile** [comment]
I wanted to avoid introducing `as ...` as it's kind of ugly  -- it's not outside the realm of possibility though

**Comment by firba1** [comment]
What would be a reasonable way of doing this? Do you think it would be too surprising to just patch this into a new version or would we want to to be behind a flag?

**Comment by asottile** [comment]
not sure, I don't think this should happen at all.  changing the import but keeping the old name seems wrong

**Comment by firba1** [comment]
The use case here I'm thinking is that I want to be able to replace imports and know that they are all in the state I expect. However, since #67 isn't fixable, I wonder if it isn't worth it after all.

**Comment by asottile** [comment]
yeah seems like it. wompwomp :/
