### ISSUE TITLE
Docs: Mention differences with 'isort'.

### ISSUE THREAD

**Issue by barseghyanartur** [asottile/reorder_python_imports#73]
Subj.

**Comment by asottile** [comment]
This is covered under [what does it do](https://github.com/asottile/reorder_python_imports#what-does-it-do) and [why this style](https://github.com/asottile/reorder_python_imports#why-this-style)

though perhaps it could also mention that [isort does dynamic analysis while this does not](https://github.com/pre-commit/mirrors-isort#classification-of-imports) but I don't really want to start any fights :P

Is there anything specific you're looking to get out of such documentation?

**Comment by barseghyanartur** [comment]
@asottile:

Please, don't get me wrong. I'm not looking for fights or disputes either. 

Just that `isort` has been there for 6 years already. I suppose you have used it as well. As a developer, I'm curios, what are the benefits of using this package over `isort`.

**Comment by asottile** [comment]
Technically this has existed for four years in open source so 🤷‍♂️ 

Is this sufficient?

> Similar to isort but uses static analysis more.

**Comment by barseghyanartur** [comment]
@asottile:

Oops. Sorry, I didn't know it's that old. Fair enough. Thanks!

**Comment by asottile** [comment]
@barseghyanartur just because I'm curious and I've noticed a flurry of activity -- is there somewhere this got linked?

**Comment by barseghyanartur** [comment]
@asottile:

Tom Christie gave you a star. You're supposed to get some traffic here. :)

![haha-2019-03-20-00-51-40](https://user-images.githubusercontent.com/4925587/54649411-63c10280-4aaa-11e9-906d-e74651cb656a.png)

**Comment by asottile** [comment]
@barseghyanartur awesome thanks! <3
