### ISSUE TITLE
Only import modules?

### ISSUE THREAD

**Issue by jtrakk** [asottile/reorder_python_imports#79]
I'm a fan of the [only-import-modules style](https://github.com/google/styleguide/blob/gh-pages/pyguide.md#22-imports). 

A [pylint plugin](https://stackoverflow.com/a/45390670/3346095) can enforce that style, but for codebases that aren't consistently using it, I wonder if it'd be possible to automatically convert them.

Could this module help me apply that style to my codebases? For example, it would replace 

```python
from collections import Counter

c = Counter()
```
with
```python
import collections

c = collections.Counter()
```

**Comment by asottile** [comment]
it's not, see #69 which attempted the same -- you essentially need to solve the halting problem to do it 100% correct

**Comment by asottile** [comment]
it's also impossible to know statically whether something is a module or not -- pylint does _dynamic_ analysis to determine that

For instance if you saw:

```python
from a.b.c import d
```

it's impossible to know whether `d` is a module or a function without actually executing the import
