### ISSUE TITLE
Allow multiple one-line imports

### ISSUE THREAD

**Issue by Dinoshauer** [asottile/reorder_python_imports#8]
I usually import modules in a single import statement like so:

```
from __future__ import absolute_imports, unicode_literals
```

`reorder-python-imports` demands each import to be placed on seperate lines. Isort has this as a config option: [**force_single_line**](https://github.com/timothycrosley/isort/wiki/isort-Settings)

**Comment by asottile** [comment]
I'd accept a PR for this.  I've mostly implemented this to satisfy yelp's style requirements but would be happy to have a cmdline option to satisfy this as well.

**Comment by asottile** [comment]
The way I'd probably implement this is to add an additional step function that is conditionally called in this case.

**Comment by asottile** [comment]
The `_get_steps` function I'm adding in #12 should make this even easier to implement: https://github.com/asottile/reorder_python_imports/pull/12/files#diff-4f8e18c653cc59b349768e425f57045cR272

**Comment by Dinoshauer** [comment]
I've had this patch laying around for a few weeks now, just haven't had the time to tell about it though.

I think the hardest thing to get my head around is where to check and parse the comma imports in the most lean way, instead of first splitting them up and then sticking them back together, I'm sure this implementation has some flaws and the tests are broken on this commit as well, I just wanted to revive the thread :)

https://github.com/Dinoshauer/reorder_python_imports/commit/6de0ef777f976b50e3314ada52fd5d578152a1d7

**Comment by asottile** [comment]
You can group them by `.module` and `isinstance(..., FromImport)` and probably put them in a `defaultdict(list)` since they're guaranteed to be sorted by the end part.

I'd do something like this:

```python
def combine_from_imports(partitions):
    def _inner():
        # write an accumulator which uses isinstance(..., FromImport) and .module == .module

    return list(_inner())

def _get_steps(...):
    # ...
    if args.combine_from_imports:
        yield combine_from_imports
```

**Comment by asottile** [comment]
I realized I presented two approaches, I'd go with the second one over the first one :)

**Comment by Dinoshauer** [comment]
I'll have a look at implementing it in ``#_get_steps`` when I get some time again

**Comment by asottile** [comment]
I'm probably not going to implement this.  The README has been updated with [this rationale](https://github.com/asottile/reorder_python_imports#why-this-style) for the current style output.

That said, it's now easier to use `isort` through pre-commit with correct import classification via [seed-isort-config](https://github.com/asottile/seed-isort-config).
