### ISSUE TITLE
Separating imports from shebang

### ISSUE THREAD

**Issue by jtrakk** [asottile/reorder_python_imports#81]
Looks like `black` is ok with 0, 1, or 2 blank lines between the shebang and the first import. But `reorder_python_imports` removes those lines. For example,

```python
#!/usr/bin/env python3


import typing as t

import attr

print("hello")

```

becomes

```python
#!/usr/bin/env python3
import typing as t

import attr

print("hello")
```

I'd like to keep those separating lines.

---
reorder-python-imports==1.5.0
python3.6

**Comment by asottile** [comment]
Duplicate of #66

**Comment by jtrakk** [comment]
Ah sorry, I missed that.

**Comment by asottile** [comment]
no problem! thanks for the issue 🎉
