### ISSUE TITLE
Dataclasses treated as external module in py37-plus mode

### ISSUE THREAD

**Issue by squeaky-pl** [asottile/reorder_python_imports#85]

**Comment by asottile** [comment]
the `--pyXX-plus` modes are only for removing `__future__` / `six` imports

the actual detection of modules is based on the interpreter which is running.  If you're running `reorder-python-imports` using a python3.6 interpreter then it will be classified as third party

If you're using it through pre-commit, you may want to utilize `language_version` / `default_language_version` to select an appropriate version of python

**Comment by squeaky-pl** [comment]
Thank you for your prompt response. I was confused and confirmed it works correctly when executed with python3.7. I also pressed enter before filling the details in GitHub UI.

**Comment by asottile** [comment]
Cheers! Thanks for the issue
