### ISSUE TITLE
Why double newline after imports if the next item is a variable?

### ISSUE THREAD

**Issue by Dinoshauer** [asottile/reorder_python_imports#9]
Just noticed now that ``reorder-python-imports`` forces 2 newlines after imports regardless if the next thing after the import is a class, function or a variable.

Just curious as I couldn't find anything in the [pep](https://www.python.org/dev/peps/pep-0008/#imports) about this, is it intended?

**Comment by asottile** [comment]
pep8 suggests separating toplevel things with two linebreaks

**Comment by Dinoshauer** [comment]
It says here ["Separate top-level function and class definitions with two blank lines."](https://www.python.org/dev/peps/pep-0008/#blank-lines)

Maybe I'm comparing this tool too much with isort? :cactus:

**Comment by asottile** [comment]
Heh perhaps.  I ran into a similar problem when implementing this [here](https://github.com/asottile/cheetah_lint/blob/master/cheetah_lint/reorder_imports.py) and this was the easiest approach.  pep8 doesn't seem to enforce either direction (maybe it should?).

**Comment by Dinoshauer** [comment]
Yeah maybe, I prefer to have a newline separating my docstrings/comments in the top from the imports and just a single newline separating imports if the next declaration is a variable

**Comment by asottile** [comment]
Actually I've thought of a more clever way to solve this.  I'm going to take a stab at a PR to solve it.
