### ISSUE TITLE
Not ordering correctly when having local dependencies installed via pip install --editable

### ISSUE THREAD

**Issue by filipcima** [asottile/reorder_python_imports#95]
Hey,

I recently noticed that reorder-python-imports doesn't behave correctly, when importing packages installed via `pip install --editable` mode. reorder-python-imports takes it as __imports from standard libraries__. Note that I didn't specify application-directory.

For example these imports:
```python
import re
import requests
import sys
import my_local_package  # installed via pip install --editable
import my_local_package2  # installed via pip install without --editable switch
```
will be reordered to:
```python
import my_local_package  # installed via pip install --editable
import re
import sys

import my_local_package2  # installed via pip install without --editable switch
import requests
```
and it should be reordered to:
```python
import re
import sys

import my_local_package   # installed via pip install --editable
import my_local_package2  # installed via pip install without --editable switch
import requests
```
If the package is installed without --editable switch, imports are reordered correctly.
The same applies when I run reorder-python-imports outside virtual env, but it's kind of annoying to always deactivate virtualenv.

**Comment by asottile** [comment]
If you can come up with a heuristic to identify editable-installed packages I'd happily take a PR in the [underlying library](https://github.com/asottile/aspy.refactor_imports/blob/598d80db8942f421436573c7c3a64a79fffdc597/aspy/refactor_imports/classify.py#L124)

I don't personally editable-install dependencies so I don't hit this.  fwiw `reorder-python-imports` works best when entirely isolated (for example via [pre-commit](https://pre-commit.com))  -- another way to isolate it is to put it in its own venv (it doesn't need to be activated to be used)

For example:

```bash
virtualenv ~/opt/venv
~/opt/venv/bin/pip install reorder-python-imports'
mkdir -p ~/bin
ln -s ~/opt/venv/bin/reorder-python-imports ~/bin/
```

As this issue isn't about `reorder-python-imports` itself I'm going to close this -- thanks again for the issue though! :tada:
