### ISSUE TITLE
Option to disable or replace relative imports with absolute ones

### ISSUE THREAD

**Issue by daviebadger** [asottile/reorder_python_imports#96]
Let's say I have:

```py
from . import X
from .y import Y
```

I would expect something like this:

```py
from my_package import X
from my_package.y import Y
```

 after passing some options to let the CLI known, what is the local package name.

**Comment by asottile** [comment]
for the same reasons as #69 -- I don't think this can't be done statically

given I don't personally use relative imports and I don't think this will be easy to do (and I don't really want to work on this feature) I'm going to close this

that said, if you want to work on a PR I'd happily take a tested one!

thanks again for the issue!
