### ISSUE TITLE
Incorrect order for application-specific imports

### ISSUE THREAD

**Issue by aklajnert** [asottile/reorder_python_imports#98]
I have the following imports in my project:
```python
import os

import yaml.error
from PySide.QtCore import Qt

from lib.observer import ReleaseEventReceiver
from .dialog import ErrorDialog
```

The `lib` directory is a directory within the application and is correctly placed in the third import group. The problem is that the `reorder_python_imports` probably want to sort this section alphabetically and places the relative import before the absolute one:  
```python
...

from .dialog import ErrorDialog
from lib.observer import ReleaseEventReceiver
```

This triggers a following pylint error:  
```
C0411: first party import "from lib.observer import ReleaseEventReceiver" should be placed before "from .dialog import ErrorDialog" (wrong-import-order)
```

I think it makes sense, to put the relative imports on the very bottom since they are probably the most important here.  

Is it intentional? Maybe there is a reason behind it and we should disable this rule in pylint?

**Comment by asottile** [comment]
yes it's intentional however there is no reason, consider using `--separate-relative`

**Comment by asottile** [comment]
the reason for the discrepancy is pylint uses `isort`'s rules -- usually if I have a code formatter for import sorting I turn off linters for it since it's a waste of time

**Comment by lucasmbrown-usds** [comment]
@asottile I'm having this same error. `--separate-relative ` does not seem to be an option for `reorder_python_imports`. Can you explain what you meant?
